### ISSUE TITLE
this site is an hack

### ISSUE THREAD

**Issue by Kdy010010** [tool-sphere/tool-sphere.github.io#1]
I am going to report this org

**Comment by duplicate2991** [comment]
but why?!!

**Comment by duplicate2991** [comment]
No hack

**Comment by Kdy010010** [comment]
if you do it on mobile you get hacked

**Comment by duplicate2991** [comment]
can you please tell me how it could be possible?

**Comment by Kdy010010** [comment]
You chose the wrong adsense
So I WAS HACKED

**Comment by duplicate2991** [comment]
OMG, I am really sorry , and thanks a lot for letting me know, i will remove the adsense 
and sorry for that
